/**
 * Dance Studio CRM - reusable studio configuration.
 * Keep studio-specific prices, rooms, classes, and members in Google Sheet
 * data tabs, not in automation code.
 */
const DANCE_STUDIO_CRM = Object.freeze({
  STUDIO_NAME: 'Dance Studio CRM',
  ATTENDANCE_SHEET: 'Attendance',
  PAYMENTS_SHEET: 'Payments',
  PACKAGES_SHEET: 'Packages',
  MEMBER_PACKAGES_SHEET: 'Member_Packages',
  CREDIT_LEDGER_SHEET: 'Credit_Ledger',
  AUTOMATION_RULES_SHEET: 'Automation_Rules',
  AUTOMATION_LOG_SHEET: 'Automation_Log',
  CHANGE_LOG_SHEET: 'Change_Log',
  LEADS_SHEET: 'Leads',
  FOLLOW_UPS_SHEET: 'Follow_ups',
  ROOM_BOOKINGS_SHEET: 'Room_Bookings',
  CLASS_SESSIONS_SHEET: 'Class_Sessions',
  CLASSES_SHEET: 'Classes',
  PACKAGE_RULE_ID: 'RULE-PKG-001',
  PACKAGE_RULE_NAME: 'Package credit deduction',
  PAYMENT_RULE_ID: 'RULE-PAY-001',
  PAYMENT_RULE_NAME: 'Payment to package entitlement',
  PACKAGE_MAINTENANCE_RULE_ID: 'RULE-PKG-MAINT-001',
  PACKAGE_MAINTENANCE_RULE_NAME: 'Daily package maintenance',
  TRIAL_FOLLOW_UP_RULE_ID: 'RULE-FOLLOWUP-001',
  TRIAL_FOLLOW_UP_RULE_NAME: 'Trial attendance follow-up',
  ROOM_CONFLICT_RULE_ID: 'RULE-ROOM-001',
  ROOM_CONFLICT_RULE_NAME: 'Room booking conflict check',
  CLASS_ROOM_SYNC_RULE_ID: 'RULE-CLASS-ROOM-001',
  CLASS_ROOM_SYNC_RULE_NAME: 'Class session room booking sync',
  CLASS_SESSION_GENERATION_RULE_ID: 'RULE-CLASS-GEN-001',
  CLASS_SESSION_GENERATION_RULE_NAME: 'Seven-day fixed class session generation',
  MEMBER_CHARGES_SHEET: 'Member_Charges',
  MEMBERS_SHEET: 'Members',
  MEMBER_REST_REQUESTS_SHEET: 'Member_Rest_Requests',
  IN_HOUSE_FEE_RULE_ID: 'RULE-INHOUSE-FEE-001',
  IN_HOUSE_FEE_RULE_NAME: 'Monthly in-house studio fee generation',
  IN_HOUSE_REST_RULE_ID: 'RULE-INHOUSE-REST-001',
  IN_HOUSE_REST_RULE_NAME: 'In-house rest lifecycle',
  LEAD_CONVERSION_RULE_ID: 'RULE-LEAD-CONVERT-001',
  LEAD_CONVERSION_RULE_NAME: 'Lead to member conversion',
  WALK_IN_RULE_ID: 'RULE-WALKIN-001',
  WALK_IN_RULE_NAME: 'Walk-in attendance charge',
  WALK_IN_PAYMENT_RULE_ID: 'RULE-WALKIN-PAYMENT-001',
  WALK_IN_PAYMENT_RULE_NAME: 'Walk-in payment reconciliation',
  TRIAL_RULE_ID: 'RULE-TRIAL-001',
  TRIAL_RULE_NAME: 'Trial attendance validation',
  SETTINGS_SHEET: 'Settings',
  IN_HOUSE_MEMBER_TYPE: 'In_House_Crew',
  CLASS_BOOKING_SOURCE: 'Class_Session',
  CREW_PRACTICE_BOOKING_TYPE: 'Crew_Practice',
  AUDIT_RULE_ID: 'RULE-AUDIT-001',
  AUDIT_RULE_NAME: 'Important field change history',
  PACKAGE_ATTENDANCE_TYPE: 'Package',
  WALK_IN_ATTENDANCE_TYPE: 'Walk_In',
  PUBLIC_MEMBER_TYPE: 'Public',
  NON_MEMBER_TYPE: 'Walk_In',
  DEMO_ACTOR_EMAIL: 'admin@example.com',
  AUDITED_FIELDS: Object.freeze({
    Members: Object.freeze(['Status', 'Phone', 'Email', 'Member_Type', 'In_House_Status']),
    Payments: Object.freeze(['Payment_Status', 'Amount_Paid', 'Package_ID']),
    Member_Packages: Object.freeze(['Status', 'Credits_Granted', 'Credits_Remaining', 'Expires_At']),
    Attendance: Object.freeze(['Attended', 'Attendance_Type', 'Payment_Status']),
    Leads: Object.freeze(['Status', 'Phone', 'Email']),
    Room_Bookings: Object.freeze(['Booking_Date', 'Start_Time', 'End_Time', 'Status', 'Payment_Status']),
    Class_Sessions: Object.freeze(['Session_Date', 'Start_Time', 'End_Time', 'Room_ID', 'Status'])
  })
});
